#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.0
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wcf")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["wcfConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<copia> copia
	{
		get
		{
			return this.GetTable<copia>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.copia")]
public partial class copia
{
	
	private decimal _idasociados;
	
	private long _cedulasociado;
	
	private decimal _salario;
	
	private System.Nullable<System.DateTime> _fechaingresoLabora;
	
	private string _nombreintegrado;
	
	public copia()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idasociados", DbType="Decimal(18,0) NOT NULL")]
	public decimal idasociados
	{
		get
		{
			return this._idasociados;
		}
		set
		{
			if ((this._idasociados != value))
			{
				this._idasociados = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulasociado", DbType="BigInt NOT NULL")]
	public long cedulasociado
	{
		get
		{
			return this._cedulasociado;
		}
		set
		{
			if ((this._cedulasociado != value))
			{
				this._cedulasociado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salario", DbType="Decimal(18,0) NOT NULL")]
	public decimal salario
	{
		get
		{
			return this._salario;
		}
		set
		{
			if ((this._salario != value))
			{
				this._salario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaingresoLabora", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaingresoLabora
	{
		get
		{
			return this._fechaingresoLabora;
		}
		set
		{
			if ((this._fechaingresoLabora != value))
			{
				this._fechaingresoLabora = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreintegrado", DbType="VarChar(105)")]
	public string nombreintegrado
	{
		get
		{
			return this._nombreintegrado;
		}
		set
		{
			if ((this._nombreintegrado != value))
			{
				this._nombreintegrado = value;
			}
		}
	}
}
#pragma warning restore 1591
